### PR TITLE
Adding Open sans as base font and fixing menus

### PR DESCRIPTION
**Pull request by tylergibson**
First style guide commits.  Adding the base font (Open Sans) to override Roboto, setting the stage for mobile and pixel density aware type, and adjusting the layout and behavior for the hambuger menu as well as the primary card + collection list.

### CODE REVIEW

**Comment by felixrieseberg** [comment]
Nice 👍🏻! I looked at the whole thing and have only two comments:
- There seems to be something funky going on with tabs & spaces - can you check that it's always 4 spaces and on the same indentation as the same level?
- I'm not sure here, so let me just ask: Do browsers download fonts on demand only, or as soon as the CSS is opened? If it's the later, I'd exclude all the currently unneeded fonts until we need them.

**Comment by tylergibson** [comment]
Hmm, I'll double check on the spacing/indents.  I'm just using notepad++ on defaults for everything.

For the fonts, it's on demand and a it's a first match cascade.  The browser only loads a font face when it's used in a selector and the. It only loads the first supported file format matched in the url cascade.  So there's very very little perf impact from the font family definitions themselves.

Sent from Outlook<http://taps.io/outlookmobile>

_____________________________

**Comment by sedouard** [comment]
@tylergibson make sure to run `npm test` before you checkin. you have code styling violations

**Comment by tylergibson** [comment]
CI build passed, on to the next thing I hope :)

**Comment by felixrieseberg** [comment]
There are still some line indents in the SASS files, but I'm fine with fixing them manually :)

**Pull request merged**
